# Generated by Django 3.0.4 on 2020-04-18 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_start', models.PositiveIntegerField()),
                ('index_end', models.PositiveIntegerField()),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='api.Table')),
            ],
        ),
        migrations.CreateModel(
            name='TableResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('table_row_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.TableRow')),
            ],
        ),
    ]
