# Generated by Django 3.0.5 on 2020-04-14 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TableAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IntegerAction',
            fields=[
                ('tableaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_table.TableAction')),
                ('number', models.IntegerField()),
            ],
            bases=('api_table.tableaction',),
        ),
        migrations.CreateModel(
            name='TextAction',
            fields=[
                ('tableaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_table.TableAction')),
                ('text', models.TextField()),
            ],
            bases=('api_table.tableaction',),
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_start', models.PositiveIntegerField()),
                ('index_end', models.PositiveIntegerField()),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_table.Table')),
            ],
        ),
        migrations.AddField(
            model_name='tableaction',
            name='table_row_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_table.TableRow'),
        ),
    ]
