# Generated by Django 3.0.5 on 2020-04-16 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('table_row_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_table.TableRow')),
            ],
        ),
        migrations.RemoveField(
            model_name='tableaction',
            name='table_row_id',
        ),
        migrations.RemoveField(
            model_name='textaction',
            name='tableaction_ptr',
        ),
        migrations.DeleteModel(
            name='IntegerAction',
        ),
        migrations.DeleteModel(
            name='TableAction',
        ),
        migrations.DeleteModel(
            name='TextAction',
        ),
    ]
